name: 3.2 branch Windows snapshot

on:
    push:
        branches:
            - 3.2

    repository_dispatch:
        types: [build_win64_snapshot]

jobs:
    build:
        runs-on: windows-2019

        steps:
            - name: Cache Qt
              id: cache-qt
              uses: actions/cache@v1
              with:
                path: ${{ github.workspace }}\Qt
                key: ${{ runner.os }}-Qt-Cache
                
            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                cached: ${{ steps.cache-qt.outputs.cache-hit }}
                version: '5.14.2'
                host: 'windows'
                arch: 'win64_mingw73'
                dir: '${{ github.workspace }}'
                modules: 'qtscript'

            - name: Clone repo
              uses: actions/checkout@v2
              with:
                ref: 3.2

            - name: Download dependencies
              shell: pwsh
              run: (new-object System.Net.WebClient).DownloadFile('https://www.dropbox.com/s/b5t6lb9e7riytq1/win64_deps.zip?dl=1', '..\win64_deps.zip')
            
            - name: Decompress dependencies
              run: 7z x -o".." ..\win64_deps.zip

            - name: Debug pwd
              run: pwd
              
            - name: Debug tree
              run: tree ..
              
            - name: Debug dir
              run: dir ..
              
            - name: Debug qmake
              run: dir D:\a\sqlitestudio\sqlitestudio\Qt\5.14.2\mingw73_64\bin
              
            - name: QMake
              run: ${{ github.workspace }}\Qt\5.14.2\mingw73_64\bin\qmake.exe --help
              
            - name: Make
              run: ${{ github.workspace }}\Qt\Tools\mingw730_64\bin\mingw32-make.exe --help
              
